In [1]:
import numpy as np
import pandas as pd
import pickle
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [17]:
# Load the dataset using Pandas
df = pd.read_csv("/content/diamonds.csv")

In [9]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [10]:
df.tail()

       carat        cut color clarity  depth  table  price     x     y     z
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [12]:
df.shape

(53940, 10)

In [13]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [3]:
# Define the input features (X) and the target variable (price)
X = df.drop(columns=["price"])
y = df["price"]

In [14]:
print("Input features (X):")
print(X.head())
print("\nTarget variable (y):")
print(y.head())

Input features (X):
   carat      cut color clarity  depth  table     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75

Target variable (y):
0    326
1    326
2    327
3    334
4    335
Name: price, dtype: int64

In [4]:
# Split the dataset into training and testing sets using a 75:25 ratio
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [15]:
print("Training set shape:")
print(X_train.shape, y_train.shape)
print("\nTesting set shape:")
print(X_test.shape, y_test.shape)

Training set shape:
(40455, 9) (40455,)

Testing set shape:
(13485, 9) (13485,)

In [5]:
# Apply data preprocessing (Encode categorical features & Scale numerical features)
numerical_features = ["carat", "depth", "table", "x", "y", "z"]
categorical_features = ["cut", "color", "clarity"]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ]
)

In [16]:
print("Preprocessor:")
print(preprocessor)

Preprocessor:
ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['carat', 'depth', 'table', 'x', 'y', 'z']),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['cut', 'color', 'clarity'])])

In [6]:
# Train a KNN Regressor model using Scikit-learn Pipeline
model_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", KNeighborsRegressor(n_neighbors=5)),
    ]
)

print("Training the model...")
model_pipeline.fit(X_train, y_train)

Training the model...

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['carat', 'depth', 'table',
                                                   'x', 'y', 'z']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['cut', 'color',
                                                   'clarity'])])),
                ('regressor', KNeighborsRegressor())])

In [7]:
# Evaluate the model
y_pred = model_pipeline.predict(X_test)
print(f"MAE: {mean_absolute_error(y_test, y_pred):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.2f}")
print(f"R2 Score: {r2_score(y_test, y_pred):.4f}")

MAE: 408.17
RMSE: 785.87
R2 Score: 0.9607

In [8]:
# Save the trained pipeline using Pickle
with open("model.pkl", "wb") as file:
  pickle.dump(model_pipeline, file)
print("Pipeline saved successfully as model.pkl!")

Pipeline saved successfully as model.pkl!

In [20]:
description_content = """Dataset Name: Diamonds Dataset
Description: Contains prices and attributes of nearly 54,000 diamonds.

Features / Columns:
- price: Price in US dollars ($326 - $18,823) [Target Variable]
- carat: Weight of the diamond (0.2 - 5.01)
- cut: Quality of the cut (Fair, Good, Very Good, Premium, Ideal)
- color: Diamond color, ranging from D (best) to J (worst)
- clarity: Measurement of how clear the diamond is (I1, SI2, SI1, VS2, VS1, VVS2, VVS1, IF)
- depth: Total depth percentage = z / mean(x, y) = 2 * z / (x + y)
- table: Width of top of diamond relative to widest point
- x: Length in 3.95 mm
- y: Width in 3.98 mm
- z: Depth in 2.43 mm
"""

with open("description.txt", "w") as f:
  f.write(description_content)